### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by tolson-vkn**
Wolfgang added to leader board.

---

Surprised to not see this yet.

I added links to the guest's medias. Mostly because I was wondering: Do I put Wolfgang or do I put Wolfgang's channel? But if I don't put `'s channel` what if people want to go to his channel as he mentioned that as his contact point in episode.

Will remove if preferred. I think how the wiki currently does hyperlink text it won't look disruptive.

### CODE REVIEW

**Comment by tolson-vkn** [comment]
Build errors. I might look at why this doesn't work tomorrow.

**Review by ironicbadger — APPROVED** [review]

**Comment by WhiteNight121** [comment]
@tolson-vkn hey is it me or did this change not show up on the wiki?

**Comment by tolson-vkn** [comment]
There were build errors so no, I don't think it ever promoted. https://github.com/selfhostedshow/wiki/actions/runs/7148874189/job/19470403552#step:4:9

I was going to try see what was broken but have not.

**Comment by WhiteNight121** [comment]
all good just wanted to make sure it was not just me.

**Pull request merged**
