### PR TITLE
Remove duplicate of beginners-contributing-guide from basic

### LINKED ISSUE #85: Two versions of beginners-contributing-guide.md and out of sync with each other.
There are two versions of `beginners-contributing-guide.md` one located at `docs/basics` and another at `docs/wiki`

These are clearly meant to be the same file. I would propose that one be chosen to be the holder of `truth` and the other converted to a reference similar to how `CONTRIBITING.md` is used for `docs/wiki/contribiting.md`
It appears that `wiki/beginners....` is the most up to date and is inline with the move from `dev` to `master` for the default branch.

This would allow for the two references. But the need to only edit a single file.

### PR DESCRIPTION
**Pull request by Bas-Man**
This closes #85

Though I would still like to have people making their changes in a new branch based off master. This would protect their local master branch. In the advent that their pull requests are not accepted, or take a long time to be accepted.
I can foresee people having potential merge conflicts down the road.

Something along the lines of
```
git checkout -b <my contribution>
```
Then after edits.
```
git push <my contribition>
```

What are you thoughts @WhiteNight121

### CODE REVIEW

**Comment by RealOrangeOne** [comment]
The link to this page should also be removed from the `CONTRIBUTING.md` file too.

**Comment by Bas-Man** [comment]
I will take a look at it in a few hours. Thanks for catching that issue.

**Comment by Bas-Man** [comment]
> The link to this page should also be removed from the `CONTRIBUTING.md` file too.

This is actually already correct and does not need to be changed. It already correctly references content in the `docs/wiki/` folder.

But I have found another issue contained within the beginners-contributing-guide.
```
#### 1.3 Merging an local repository into your Fork

This Section will "merge" the local changes to your fork (your github repo that was made above in [section 1.1](https://github.com/selfhostedshow/wiki/tree/master/docs\basics/beginners-contributing-guide/#11-fork-clone-the-self-hosted-show-wiki))
```
This link is broken; even in the exist live site. 
Will investigate. Since I am not sure what this content was.

**Comment by Bas-Man** [comment]
> > The link to this page should also be removed from the `CONTRIBUTING.md` file too.
> 
> This is actually already correct and does not need to be changed. It already correctly references content in the `docs/wiki/` folder.
> 
> But I have found another issue contained within the beginners-contributing-guide.
> 
> ```
> #### 1.3 Merging an local repository into your Fork
> 
> This Section will "merge" the local changes to your fork (your github repo that was made above in [section 1.1](https://github.com/selfhostedshow/wiki/tree/master/docs\basics/beginners-contributing-guide/#11-fork-clone-the-self-hosted-show-wiki))
> ```
> 
> This link is broken; even in the exist live site.
> Will investigate. Since I am not sure what this content was.

I think I have resolved this internal issue with the latest commit.

**Review by RealOrangeOne — APPROVED** [review]

**Review by BCNelson — APPROVED** [review]

**Pull request merged**
