### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by WhiteNight121**
changed from:

```bash
git clone https://github.com/selfhostedshow/wiki wiki &&\
	cd wiki
```
to:

```bash
git clone https://github.com/selfhostedshow/wiki && cd wiki
```

### CODE REVIEW

**Comment by py-crash** [comment]
@WhiteNight121 why did you close it?

**Comment by WhiteNight121** [comment]
ya i have not used git much i thought i was supposed to....

**Comment by py-crash** [comment]
Just wait someone from the backend group to review it and will be merged

**Comment by WhiteNight121** [comment]
@py-crash ok thanks

**Pull request merged**
